enum ErrorCode {
    COMMON_CODE_OK = 0,
    COMMON_NO_LOGIN = 1,
    COMMON_UNKNOW_ERROR = 2,
    COMMON_DATA_SEND_FAILD = 3,
    COMMON_INVALID_PROTOCAL = 4,

    BREOKEN_CONNECT_TO_SERVER = 201,
    BAD_CONNECT_TO_SERVER = 202,
    CLIENT_SDK_NO_INITIALED = 203,
    LOCAL_NETWORK_NOT_WORKING = 204,
    TO_SERVER_NET_INFO_NOT_SETUP = 205,

    RESPONSE_FOR_UNLOGIN = 301,
}

export default ErrorCode;