enum ProtocalType {
    FROM_CLIENT_TYPE_OF_LOGIN = 0,
    FROM_CLIENT_TYPE_OF_KEEP$ALIVE = 1,
    FROM_CLIENT_TYPE_OF_COMMON$DATA = 2,
    FROM_CLIENT_TYPE_OF_LOGOUT = 3,
    FROM_CLIENT_TYPE_OF_RECIVED = 4,
    FROM_CLIENT_TYPE_OF_ECHO = 5,

    FROM_SERVER_TYPE_OF_RESPONSE$LOGIN = 50,
    FROM_SERVER_TYPE_OF_RESPONSE$KEEP$ALIVE = 51,
    FROM_SERVER_TYPE_OF_RESPONSE$FOR$ERROR = 52,
    FROM_SERVER_TYPE_OF_RESPONSE$ECHO = 53,
    FROM_SERVER_TYPE_OF_RESPONSE$RECIVED = 54
}

export default ProtocalType;